### ISSUE TITLE
0.3.0 release on pypi

### ISSUE THREAD

**Issue by dlamblin** [grumpyhome/grumpy#138]
Which tag or release number does the https://pypi.org/project/grumpy-runtime/ for 0.3.0 come from? I can only see a v0.2.2 in the project.

**Comment by alanjds** [comment]
Sorry for that. Looks like I had not pushed the tag. Fixed.

It cames from https://github.com/grumpyhome/grumpy/commit/3dc88e66bbaba62ea11324091176acf0403d3f5f, issued on Jul 24, 2018

**Comment by abitrolly** [comment]
`master` still bears 0.2.2 version tag, because the version bump was on separate commit that was not merged https://github.com/grumpyhome/grumpy/compare/master...v0.3.0

**Comment by abitrolly** [comment]
I added the necessary merge to #139 with other cleanups.

**Comment by alanjds** [comment]
#139 was merged. Thanks @abitrolly.
