### ISSUE TITLE
how to use externs or interop for go code?

### ISSUE THREAD

**Issue by 6umpukc-uHKBu3umop** [grumpyhome/grumpy#148]
if i want to use standart go libs with this grympy code - how i can do this?

**Comment by alanjds-ps** [comment]
Hi, 6ump.

You can import from `'__go__'` to get stuff from Golang libs.

Please take a look on the math.py implementation, that uses `from '__go__/math' import`: https://github.com/grumpyhome/grumpy/blob/7370a936adc980d998f769efc56db0d820cce053/grumpy-runtime-src/lib/math.py#L15

**Comment by alanjds** [comment]
Hi, 6ump.

You can import from `'__go__'` to get stuff from Golang libs.

Please take a look on the math.py implementation, that uses `from '__go__/math' import`: https://github.com/grumpyhome/grumpy/blob/7370a936adc980d998f769efc56db0d820cce053/grumpy-runtime-src/lib/math.py#L15

**Comment by 6umpukc-uHKBu3umop** [comment]
> from '__go__/math' import Pi
> print Pi
> 

this output 

> grumpy run test.py
> 3.14159265359
> 

but this 
```

 import "__go__/encoding/hex"
 print hex.Dump('foobar')

```
output error
grumpy run test.py

/tmp/tmp8Y9Chn__pycache__/gopath/src/__python__/__main__/module.go:4:2: cannot find package "__python__/__go__/encoding/hex" in any of:
	/usr/lib/go/src/__python__/__go__/encoding/hex (from $GOROOT)
	/tmp/tmp8Y9Chn__pycache__/gopath/src/__python__/__go__/encoding/hex (from $GOPATH)
	/home/user/.local/lib/python2.7/site-packages/grumpy_runtime/data/gopath/src/__python__/__go__/encoding/hex

**Comment by alanjds** [comment]
Can you post the output of `grumpy -v debug run test.py` instead?

**Comment by 6umpukc-uHKBu3umop** [comment]
```
grumpy -v debug fail.py                                                                                                                                            :(
info: GOPATH: /home/user/.local/lib/python2.7/site-packages/grumpy_runtime/data/gopath
info: __main__ pycache folder: /tmp/tmphOSzQ___pycache__
debug: Should transpile '__main__'
debug: Dependencies file regenerated
info: `go run` GOPATH=/tmp/tmphOSzQ___pycache__/gopath:/home/user/.local/lib/python2.7/site-packages/grumpy_runtime/data/gopath
debug: Starting subprocess: `go run /tmp/tmphOSzQ___pycache__/gopath/src/__python__/main.go`
/tmp/tmphOSzQ___pycache__/gopath/src/__python__/__main__/module.go:4:2: cannot find package "__python__/__go__/encoding/hex" in any of:
	/usr/lib/go/src/__python__/__go__/encoding/hex (from $GOROOT)
	/tmp/tmphOSzQ___pycache__/gopath/src/__python__/__go__/encoding/hex (from $GOPATH)
	/home/user/.local/lib/python2.7/site-packages/grumpy_runtime/data/gopath/src/__python__/__go__/encoding/hex

```

**Comment by 6umpukc-uHKBu3umop** [comment]
i found one folder with __python__/__go__

and here is this files

/home/user/.local/lib/python2.7/site-packages/grumpy_runtime/data/gopath/pkg/linux_amd64/__python__/__go__

```
.
./math
./math/rand.a
./io
./io/ioutil.a
./reflect.a
./grumpy.a
./time.a
./math.a
./syscall.a
./unicode.a
./os.a
./runtime.a
./path
./path/filepath.a
./sync.a

```
