### ISSUE TITLE
find: compiler: No such file or directory

### ISSUE THREAD

**Issue by corona10** [grumpyhome/grumpy#6]
Since compiler directory move to `https://github.com/grumpyhome/grumpy/tree/master/grumpy-tools-src/grumpy_tools/compiler`

We have to update  the Makefile of `https://github.com/grumpyhome/grumpy/blob/master/grumpy-runtime-src/Makefile`
Also, it should make to enable to run unit tests also.

I think that @alanjds is a proper person to do it. I don't know the history which is related with why the compiler directory is moved.

**Comment by alanjds** [comment]
Lots of the Makefile stuff got unnecessary after `grumpy-tools` became a separate package.

This compiler folder is no longer used, nor most of the bin folder.

My Makefile wisdom is not par for this one, but I will chop the compiler part and let's see if it still works :wink:

**Comment by alanjds** [comment]
Kudos @andgrew
