### ISSUE TITLE
this is not working. because bool(AssertionError) is true

### ISSUE THREAD

**Issue by alanjds** [grumpyhome/grumpy#67]
_google/grumpy#405 opened by @rishatik92 on Jun 6_

https://github.com/google/grumpy/blob/3ec87959189cfcdeae82eb68a47648ac25ceb10b/testing/list_test.py#L53

**Comment by alanjds** [comment]
Sorry @rishatik92, I do not understand what is wrong:
```
$ python -c 'print bool(AssertionError)'
True
$ grumpy -c 'print bool(AssertionError)'
True
```
This seems just right. Can you elaborate please?

**Comment by rishatik92** [comment]
i was just want to say that  assert AssertionError - will never raised
because:
>>> bool(AssertionError) True

пн, 3 сент. 2018 г. в 1:52, Alan Justino da Silva <notifications@github.com

**Comment by alanjds** [comment]
I see. It looks to be testing if the `list` exceptions are being raised correctly. The test should be doing `assert False, 'an exception should raise on last line`, not `assert AssertionError`.

Thanks for pointing

**Comment by rishatik92** [comment]
)) glad to help

пн, 3 сент. 2018 г. в 16:54, Alan Justino da Silva <notifications@github.com
