### ISSUE TITLE
Implement the 'reverse' option for sorted()

### ISSUE THREAD

**Issue by alanjds** [grumpyhome/grumpy#82]
_google/grumpy#162 opened on Jan 18, 2017 by @MirkoDziadzka_

Add the 'reverse' option to 'sorted()'

I'm not sure if this violates the 'stable sort definition in Python. 
On the other hand, this is probably only relevant when key or cmp gets implemented.

**Comment by alanjds** [comment]
<a href="https://github.com/trotterdylan"><img src="https://avatars2.githubusercontent.com/u/117627?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [trotterdylan](https://github.com/trotterdylan)**
_Friday Jan 20, 2017 at 16:17 GMT_

----

That all sounds good. Let me know when I should review again.

**Comment by funny-falcon** [comment]
While #102 is merged, it is not proper implementation, even without implementation of key or cmp:
```
$ python -c 'print sorted([1,1.0,2,2.0], reverse=True)'
[2, 2.0, 1, 1.0]
$ grumpy-runtime-src/build/bin/grumprun -c 'print sorted([1,1.0,2,2.0], reverse=True)'
[2.0, 2, 1.0, 1]
```
It will certainly affect types which implements comparison methods.

**Comment by alanjds** [comment]
:/ 
It may be about stability too. The sort code should be checked.

**Comment by alanjds** [comment]
Closing in favor of #120
