### ISSUE TITLE
Add pow builtin

### ISSUE THREAD

**Issue by alanjds** [grumpyhome/grumpy#92]
_google/grumpy#373 opened on Jul 30, 2017 by @aisk • Changes requested_

**Comment by alanjds** [comment]
<a href="https://github.com/aisk"><img src="https://avatars0.githubusercontent.com/u/699636?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [aisk](https://github.com/aisk)**
_Thursday Sep 07, 2017 at 16:33 GMT_

----

@trotterdylan Ready for review!

**Comment by aisk** [comment]
Feels happy to see grumpy is back to life! And looks like my PR is merged, so this could be closed?

**Comment by alanjds** [comment]
Sure!

We still need more hands, but at least it's not abandoned :)
