### ISSUE TITLE
Add token lib

### ISSUE THREAD

**Issue by alanjds** [grumpyhome/grumpy#97]
_google/grumpy#394 opened on Feb 5 by @nagayev2002_

**Comment by alanjds** [comment]
<a href="https://github.com/googlebot"><img src="https://avatars3.githubusercontent.com/u/5384588?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [googlebot](https://github.com/googlebot)**
_Monday Feb 05, 2018 at 17:44 GMT_

----

Thanks for your pull request.  It looks like this may be your first contribution to a Google open source project. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: **Please visit <https://cla.developers.google.com/> to sign.**

Once you've signed, please reply here (e.g. `I signed it!`) and we'll verify.  Thanks.

---

- If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address on your commit.  Check [your existing CLA data](https://cla.developers.google.com/clas) and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
- If your company signed a CLA, they designated a Point of Contact who decides which employees are authorized to participate. You may need to contact the Point of Contact for your company and ask to be added to the group of authorized contributors. If you don't know who your Point of Contact is, direct the project maintainer to go/cla#troubleshoot. The email used to register you as an authorized contributor must be the email used for the Git commit.
- In order to pass this check, please resolve this problem and have the pull request author add another comment and the bot will run again. If the bot doesn't comment, it means it doesn't think anything has changed.

**Comment by alanjds** [comment]
<a href="https://github.com/nagayev2002"><img src="https://avatars2.githubusercontent.com/u/16555544?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nagayev2002](https://github.com/nagayev2002)**
_Monday Feb 05, 2018 at 17:49 GMT_

----

@googlebot I signed it!

**Comment by alanjds** [comment]
<a href="https://github.com/googlebot"><img src="https://avatars3.githubusercontent.com/u/5384588?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [googlebot](https://github.com/googlebot)**
_Monday Feb 05, 2018 at 17:49 GMT_

----

CLAs look good, thanks!

**Comment by nagayev** [comment]
ping

**Comment by alanjds** [comment]
pong.

**Comment by nagayev** [comment]
Should I need create a PR for this issue?
Or is this repository dead?

**Comment by alanjds** [comment]
>Should I need create a PR for this issue?

If you create a PR and it passes the CI, I will review it and possibly merge.

>Or is this repository dead?

Not dead, as I and other keep an eye on it, point parts of it when specific questions arrive and so on.
Would love to see it going further, however _I_ am not personally pushing Grumpy forward this days.

When you push your PR, the CI may complain about Golang versions, for example. Once it got green, I invest time to review and merge.

**Comment by nagayev** [comment]
@alanjds OK. I will be preparing my PR for a few days.

**Comment by alanjds** [comment]
Merged https://github.com/grumpyhome/grumpy/pull/155, although the PR fails on some Python 2.7->3.X issue.

Will close here, as the failure root cause is being tracked on https://github.com/grumpyhome/grumpy/issues/135.

**Comment by alanjds** [comment]
Thanks @nagayev for the effort
